import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
import Script from "next/script";
import { PHProvider } from './provider'
import dynamic from 'next/dynamic'

const PostHogPageView = dynamic(() => import('./PostHogPageView'), {
  ssr: false,
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "thePantry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <PHProvider>
      <body className={inter.className}>
      <div style={{paddingTop: '50px'}}>
      <Navbar />
      </div>
      <PostHogPageView /> 
        {children}
        </body>
        </PHProvider>
    </html>
  );
}
